FROM node:18-alpine AS builder

WORKDIR /app

# Install production dependencies
COPY package*.json ./
RUN npm install --only=production

# Copy app source
COPY . .

# --- Final Image ---
FROM node:18-alpine

WORKDIR /app

# Copy built assets
COPY --from=builder /app .

# Expose port and start app
EXPOSE 5000
CMD ["npm", "start"]